# An example of ClusterConfig object using an existing VPC:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-test-eks-2
  region: us-east-1

vpc:
  id: "vpc-03835750fb26b5431" # (optional, must match VPC ID used for each subnet below)
  cidr: "10.0.0.0/16" # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    # private:
    #   us-east-1d:
    #     id: "subnet-0c9f5980649b029a3"
    #     cidr: "10.0.1.0/24" # (optional, must match CIDR used by the given subnet)
    public:
      us-east-1a:
        id: "subnet-0297e20d6a3e70a8c"
        cidr: "10.0.122.0/24" # (optional, must match CIDR used by the given subnet)
      us-east-1b:
        id: "subnet-0fc58079bd72fbee2"
        cidr: "10.0.142.0/24" # (optional, must match CIDR used by the given subnet)
      us-east-1c:
        id: "subnet-0d5f33a9ca898d402"
        cidr: "10.0.74.0/24" # (optional, must match CIDR used by the given subnet)
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    # privateNetworking: true # if only 'Private' subnets are given, this must be enabled
