CREATE TABLE public.people (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" text NULL,
	biography text NULL,
	picture text NULL,
	dateofbirth timestamp NOT NULL,
	CONSTRAINT pk_people PRIMARY KEY (id)
);

INSERT INTO public.people (id,"name",biography,picture,dateofbirth) VALUES	 
	 (1,'Tom Holland','This is a biography.','http://yonatan-s3-blazor-course.s3.amazonaws.com/movies/actors/TomHolland.jpg','1970-12-15 00:00:00'),
	 (2,'Samuel L. Jackson','Another biography','http://yonatan-s3-blazor-course.s3.amazonaws.com/movies/actors/SamuelL.Jackson.jpg','1945-02-04 00:00:00'),
	 (5,'Al Pacino','One of the best actors in the history of modern film.','http://yonatan-s3-blazor-course.s3.amazonaws.com/movies/actors/AlPacino.jpg','1942-03-12 00:00:00'),
	 (6,'Andy Garcia','Famous Spanish American actor from The Godfather III','http://yonatan-s3-blazor-course.s3.amazonaws.com/movies/actors/AndyGarcia.jpg','1957-03-14 00:00:00');